export const ALL_TRAITS: string[] = [
  "Baker", "Artist", "Gamer", "Poet", "Song-writer", "Witch",
  "Painter", "Sculptor", "Photographer", "Filmmaker", "Animator", "Illustrator",
  "Musician", "Guitarist", "Pianist", "Drummer", "Vocalist", "DJ",
  "Writer", "Novelist", "Blogger", "Journalist", "Screenwriter", "Storyteller",
  "Dancer", "Choreographer", "Actor", "Comedian", "Cosplayer", "Streamer",
  "Crafter", "Knitter", "Weaver", "Embroiderer", "Jeweler", "Candle-maker",
  "Gardener", "Florist", "Botanist", "Herbalist", "Forager", "Beekeeper",
  "Chef", "Barista", "Mixologist", "Chocolatier", "Pastry Chef", "Food Critic",
  "Hiker", "Climber", "Swimmer", "Cyclist", "Runner", "Skater",
  "Archer", "Fencer", "Martial Artist", "Wrestler", "Boxer", "Gymnast",
  "Reader", "Librarian", "Historian", "Philosopher", "Linguist", "Mythologist",
  "Astronomer", "Astrologer", "Tarot Reader", "Crystal Collector", "Rune Caster", "Diviner",
  "Coder", "Hacker", "Game Developer", "UI Designer", "Web Designer", "3D Modeler",
  "Collector", "Trader", "Archaeologist", "Treasure Hunter", "Puzzle Solver", "Escape Artist",
  "Volunteer", "Activist", "Environmentalist", "Healer", "Therapist", "Empath",
  "Traveler", "Explorer", "Sailor", "Survivalist", "Camper", "Stargazer",
  "Paranormal Investigator", "Cryptid Hunter", "Urban Explorer", "Storm Chaser", "Diver", "Spelunker",
];
